name: CI/CD Diagnóstico Médico

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt
        pip install pytest requests

    - name: Ejecutar pruebas
      run: pytest test_app.py

    - name: Comentar inicio de CI en PR
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ✅ CI/CD en acción. Ejecutando tareas …

    - name: Comentar éxito de CI en PR
      if: success() && github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          🎉 CI/CD terminado con éxito.

  docker_publish:
    needs: pruebas
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Iniciar sesión en GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Construir imagen Docker
        run: docker build -t ghcr.io/carlosvelez1999/diagnostico-medico:latest .

    - name: Subir imagen a GitHub Packages
        run: docker push ghcr.io/carlosvelez1999/diagnostico-medico:latest
